production:
    #host: 'support.softwaregroup-bg.com'
    host: '192.168.10.227'
    port: '443'
    communication: 'https'
    tracker: "Status update"
    extraPath: "/redmine"
development:
    host: '192.168.10.227'
    port: '443'
    communication: 'https'
    tracker: "Status update"
    extraPath: "/redmine"
